### ISSUE TITLE
Missing ) in the hw00.py code

### ISSUE THREAD

**Issue by kalikhademi** [FoundationsMachineLearning-Fa18/LectureNotes#1]
Hey, 

The ")" parenthesis is missing on line 11. This makes an error for the program. 
def hw00():

	''' Homework 00 for Foundations of Machine Learning, Fall 2018
		Provide information on your background in programming, python, git, and machine learning. 
		Provide insight into what you are hoping to learn in this class this semester. 
	 	Submit your assignment as described in class by pushing to github. 
Here is the correct code:

	print('My name is [your name]')
	print('I am a [undergraduate/masters/PhD] student majoring in [your major] in the Department of [your department].')
	print('I have [no/some/extensive] programming experience in general.')
	print('I have [no/some/extensive] python programming experience.')
	print('I have [no/some/extensive] experience with using version control software')
	print('I have [no/some/extensive] experience with git.')
	print('I have [no/some/extensive] experience in machine learning.')
	print('My github username is [username].')
	print('I am excited to learn the following in this class: [your response]')

if __name__ == '__main__':
	hw00()

**Comment by alinazare** [comment]
good catch.  this was part of the assignment to verify the code ran.  we purposefully removed the closing parenthesis.

**Comment by kalikhademi** [comment]
Ok, I just wanted to double check it :)
